version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gitsubmodule
    directory: include/
    schedule:
      interval: weekly
